apiVersion: 1

datasources:
  - name: Mimir
    type: mimir
    #access: proxy
    orgId: 1
    url: http://nginx:9009/prometheus
    version: 1
    editable: true
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      alertmanagerUid: "alertmanager"
    secureJsonData:
      httpHeaderValue1: "test"
    isDefault: true
  - name: Mimir Alertmanager
    uid: alertmanager
    type: alertmanager
    #access: proxy
    orgId: 1
    url: http://nginx:8080
    version: 1
    editable: true
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      implementation: "mimir"
    secureJsonData:
      httpHeaderValue1: "test"
